# Simple, no-dependency config to execute a file

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - run: |
          git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" .
          ./run
